/**
 * Verbatim REPL banner and help text from the original Scala TaskView
 * (src/main/scala/minicalc/repl/REPL.scala — HelpText). Kept identical so the
 * browser REPL's `:help` matches the real interpreter exactly.
 *
 * Commands that depend on the task/workflow engine are listed here for
 * fidelity but are not executable in this static browser demo.
 */

const BORDER = "=".repeat(80);

export const WELCOME: string[] = [
  "Welcome to TaskView!",
  "Type :help for help, :quit to exit",
];

export const HELP: string = [
  BORDER,
  "|                   TaskView REPL - Commands and Syntax                        |",
  BORDER,
  "|                                                                              |",
  "| COMMANDS                                                                     |",
  "| --------                                                                     |",
  "| :help              Show this help message                                    |",
  "| :demo              Run interactive demonstration of all features             |",
  "| :help full         Show detailed help with examples                          |",
  "| :env               List current variable bindings                            |",
  "| :clear             Clear all definitions (variables, tasks, workflows)       |",
  "| :quit, :q          Exit TaskView                                             |",
  "|                                                                              |",
  "| :tasks             Show all defined tasks with their configuration           |",
  "| :clear-tasks       Clear all task definitions                                |",
  "| :workflows         Show all defined workflows                                |",
  "| :run <name>        Execute a workflow by name                                |",
  "|                                                                              |",
  "| :stats             Show execution statistics                                 |",
  "| :reset-stats       Reset execution statistics                                |",
  "|                                                                              |",
  "| :settings          Show current REPL settings                                |",
  "| :set <name> <val>  Change a setting (true/false, on/off, 1/0)                |",
  "|                                                                              |",
  "| QUICK START                                                                  |",
  "| -----------                                                                  |",
  "| > 1 + 2 * 3                  Arithmetic                                      |",
  "| > let x = 5 in x * 2         Variables                                       |",
  "| > define task t1 = 42        Define a task                                   |",
  "| > execute t1                 Execute a task                                  |",
  "|                                                                              |",
  "| Type ':help full' for detailed syntax and examples                           |",
  "|                                                                              |",
  BORDER,
].join("\n");

export const HELP_FULL: string = [
  BORDER,
  "|                   TaskView REPL - Commands and Syntax                        |",
  BORDER,
  "|                                                                              |",
  "| COMMANDS                                                                     |",
  "| --------                                                                     |",
  "| :help              Show this help message                                    |",
  "| :demo              Run interactive demonstration of all features             |",
  "| :env               List current variable bindings                            |",
  "| :clear             Clear all definitions (variables, tasks, workflows)       |",
  "| :quit, :q          Exit TaskView                                             |",
  "|                                                                              |",
  "| :tasks             Show all defined tasks with their configuration           |",
  "| :clear-tasks       Clear all task definitions                                |",
  "| :workflows         Show all defined workflows                                |",
  "| :run <name>        Execute a workflow by name                                |",
  "|                                                                              |",
  "| :stats             Show execution statistics                                 |",
  "| :reset-stats       Reset execution statistics                                |",
  "|                                                                              |",
  "| :settings          Show current REPL settings                                |",
  "| :set <name> <val>  Change a setting (true/false, on/off, 1/0)                |",
  "|                                                                              |",
  "| SETTINGS                                                                     |",
  "| --------                                                                     |",
  "| continue-on-error  Continue executing tasks even when some fail              |",
  "| verbose            Show type information with values                         |",
  "| show-timing        Show execution time for operations                        |",
  "|                                                                              |",
  "| EXPRESSIONS                                                                  |",
  "| -----------                                                                  |",
  "| 1 + 2 * 3                    Arithmetic (evaluates to 7)                     |",
  "| true && false                Logical operations                              |",
  "| 5 > 3                        Comparisons (evaluates to true)                 |",
  "| if x > 0 then x else 0       Conditionals                                    |",
  "| let x = 10 in x * 2          Local variable bindings                         |",
  "|                                                                              |",
  "| TASK DEFINITIONS                                                             |",
  "| ----------------                                                             |",
  "| define task myTask = <expr>                                                  |",
  "|     with priority High|Normal|Low       (optional)                           |",
  "|     depends on task1, task2             (optional)                           |",
  "|     timeout 30                          (optional, in seconds)               |",
  "|     retry 3 backoff 5                   (optional)                           |",
  "|     exponential = true                  (optional, default false)            |",
  "|                                                                              |",
  "| TASK EXECUTION                                                               |",
  "| --------------                                                               |",
  "| execute myTask               Execute a single task                           |",
  "| sequence [t1, t2, t3]        Execute tasks sequentially                      |",
  "| parallel [t1, t2, t3]        Execute tasks in parallel                       |",
  "| schedule <expr> with FIFO    Schedule with FIFO strategy                     |",
  "| schedule <expr> with PRIORITY Schedule with priority strategy                |",
  "|                                                                              |",
  "| WORKFLOWS                                                                    |",
  "| ---------                                                                    |",
  "| define workflow myFlow = sequence [task1, task2]                             |",
  "| :run myFlow                  Execute the workflow                            |",
  "|                                                                              |",
  "| EXAMPLES                                                                     |",
  "| --------                                                                     |",
  "| # Basic arithmetic and variables                                             |",
  "| > let x = 5 in x * 2                                                         |",
  "| 10.0                                                                         |",
  "|                                                                              |",
  "| > if 10 > 5 then true else false                                             |",
  "| true                                                                         |",
  "|                                                                              |",
  "| # Task definition with all features                                          |",
  "| > define task fetchData = 42 with priority High timeout 30 retry 3 backoff 5 |",
  "| Task(fetchdata-...)                                                          |",
  "|                                                                              |",
  "| > define task processData = 100 depends on fetchData                         |",
  "| Task(processdata-...)                                                        |",
  "|                                                                              |",
  "| > :tasks                                                                     |",
  "| fetchData [Priority: High, Dependencies: none, Timeout: 30 seconds,          |",
  "|            Retry: 3 attempts (linear, 5 seconds)]                            |",
  "| processData [Priority: Normal, Dependencies: fetchData, Timeout: none,       |",
  "|              Retry: none]                                                    |",
  "|                                                                              |",
  "| # Task execution                                                             |",
  "| > execute fetchData                                                          |",
  "| Task fetchData succeeded with 42.0 in ...                                    |",
  "|                                                                              |",
  "| # Workflow creation and execution                                            |",
  "| > define workflow pipeline =                                                 |",
  "|                           sequence [execute fetchData, execute processData]  |",
  "| Workflow(pipeline)                                                           |",
  "|                                                                              |",
  "| > :run pipeline                                                              |",
  "| TaskList(2 tasks)                                                            |",
  "|                                                                              |",
  "| # REPL settings                                                              |",
  "| > :set verbose true                                                          |",
  "| Setting updated. REPL Settings:                                              |",
  "|   continue-on-error = false                                                  |",
  "|   verbose           = true                                                   |",
  "|   show-timing       = false                                                  |",
  "|                                                                              |",
  "| > 42                                                                         |",
  "| 42.0 : Number                                                                |",
  "|                                                                              |",
  "| > :set show-timing true                                                      |",
  "| Setting updated. ...                                                         |",
  "|                                                                              |",
  "| > 1 + 2                                                                      |",
  "| 3.0                                                                          |",
  "| (completed in 1.2ms)                                                         |",
  "|                                                                              |",
  "| # Advanced: Parallel execution with priorities                               |",
  "| > define task highPrio = 1 with priority High                                |",
  "| > define task lowPrio = 2 with priority Low                                  |",
  "| > schedule parallel [execute highPrio, execute lowPrio] with PRIORITY        |",
  "| TaskList(2 tasks)                                                            |",
  "|                                                                              |",
  "| # Statistics monitoring                                                      |",
  "| > :stats                                                                     |",
  "| Execution Statistics:                                                        |",
  "|   Tasks Started:   4                                                         |",
  "|   Tasks Completed: 4                                                         |",
  "|   Tasks Failed:    0                                                         |",
  "|   Average Duration: 150 milliseconds                                         |",
  "|   Currently Running: 0                                                       |",
  "|                                                                              |",
  BORDER,
].join("\n");

/** Commands that exist in the full Scala REPL but need its task engine. */
export const SCALA_ONLY_COMMANDS = new Set([
  ":demo",
  ":tasks",
  ":clear-tasks",
  ":workflows",
  ":run",
  ":stats",
  ":reset-stats",
  ":settings",
  ":set",
]);
